#-------------------------------
# General Site Settings
title: Chris Delgado
description: "Hi I'm Chris, and this is my project portfolio. Included below are interesting projects that I've recently undertaken. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: <span style="color:#f58506"> Projects </span>
resume_url: /docs/Chris_Delgado_Resume.pdf
avatar_image: /img/ProfilePicture.jpeg

#------------------------------- 
# Contact links
blog: "https://cdelgado611.wixsite.com/gettingbetter/"
linkedln: "https://www.linkedin.com/in/cdelgado2/" # Add your linkedln handle
github: "https://github.com/chris-delgado/"  # Add your github handle

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  
paginate: 4
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
